Modmata: modmata::ModmataClass Class Reference
modmata::ModmataClass Class Reference
Base class for a host computer to control this (LattePanda's Arduino Leonardo) device.
#include <Modmata.h>
Public Member Functions
void begin (int baud)
Begin listening for a Modmata connection over serial/USB.
void attach (uint8_t command, struct registers(*fn)(uint8_t argc, uint8_t *argv))
Assign a function to a command number. Standard commands have default functions, but those can be overwritten here, or more commands can be added.
void processInput ()
Read the command and args sent and execute the corresponding callback function, store the results of which in holding functions to be communicated with the host.
bool available ()
Private Attributes
registers(* callbackFunctions [20])(uint8_t argc, uint8_t *argv)
An array of references to callback functions indexed by their function code number. Use 'Modmata.attach(function_code, &function)' to add your own callback functions.
ModbusSerial mb
Object representing an interactive Modbus connection over Serial.
Detailed Description
Base class for a host computer to control this (LattePanda's Arduino Leonardo) device.
Definition at line 10 of file Modmata.h.
Member Function Documentation
attach()
void ModmataClass::attach (uint8_t command, struct registers(*)(uint8_t argc, uint8_t *argv) fn)
Assign a function to a command number. Standard commands have default functions, but those can be overwritten here, or more commands can be added.
Parameters
command The modbus command being assigned a function
fn A pointer to the function to be called when the command is recieved
Definition at line 75 of file Modmata.cpp.
References callbackFunctions.
available()
bool ModmataClass::available ()
Update modbus registers and check if a command has been received
Remarks
Will return false unless there is a Command function code besides IDLE in Hreg 0 and there was data received since the last time mb.task() was called
Returns
True or false
Definition at line 123 of file Modmata.cpp.
References mb.
begin()
void ModmataClass::begin (int baud)
Begin listening for a Modmata connection over serial/USB.
Remarks
This is configured to be used between a host computer and Arduino Leonardo using a USB connector (hardwired in the case of the LattePanda Delta 3.) The Leonardo is different from most other Arduinos in the usage of the serial connection, so if you modify this code, please keep that in mind.
Parameters
baud Set the baud rate of the listening serial connection
Definition at line 34 of file Modmata.cpp.
References functions::analogRead(), functions::analogWrite(), callbackFunctions, functions::digitalRead(), functions::digitalWrite(), mb, functions::pinMode(), functions::servoAttach(), functions::servoDetach(), functions::servoRead(), functions::servoWrite(), functions::spiBegin(), functions::spiEnd(), functions::spiSettings(), functions::spiTransferBuf(), functions::wireBegin(), functions::wireEnd(), functions::wireRead(), functions::wireSetClock(), and functions::wireWrite().
processInput()
void ModmataClass::processInput ()
Read the command and args sent and execute the corresponding callback function, store the results of which in holding functions to be communicated with the host.
Definition at line 84 of file Modmata.cpp.
References callbackFunctions, registers::count, mb, and registers::value.
Member Data Documentation
callbackFunctions
registers(* modmata::ModmataClass::callbackFunctions[20])(uint8_t argc, uint8_t *argv) private
An array of references to callback functions indexed by their function code number. Use 'Modmata.attach(function_code, &function)' to add your own callback functions.
Definition at line 15 of file Modmata.h.
Referenced by attach(), begin(), and processInput().
mb
ModbusSerial modmata::ModmataClass::mb private
Object representing an interactive Modbus connection over Serial.
Definition at line 18 of file Modmata.h.
Referenced by available(), begin(), and processInput().
The documentation for this class was generated from the following files:
Modmata.h
Modmata.cpp