Modmata: Functions.h File Reference
Functions.h File Reference
Header file for 'Functions.cpp'.
#include <stdlib.h>
#include <stdint.h>
#include <Arduino.h>
#include <Servo.h>
#include <Wire.h>
#include <SPI.h>
Classes
struct registers
A data structure to describe function arguments and return values.
struct spi_settings
A data structure to describe a SPI connection's configuration settings. Essentially the same as Arduino's 'SPIsettings' object.
Macros
#define makeDWord(i0, i1, i2, i3) ((uint32_t) (i0 << 24 | i1 << 16 | i2 << 8 | i3))
Combine four 8-bit integral types into one 32-bit integral type, or in simpler terms, reassemble a uint32_t from four uint8_t's.
#define IDLE 0
#define PINMODE 1
#define DIGITALWRITE 2
#define DIGITALREAD 3
#define ANALOGREFERENCE 4
#define ANALOGWRITE 5
#define ANALOGREAD 6
#define SERVOATTACH 7
#define SERVODETACH 8
#define SERVOWRITE 9
#define SERVOREAD 10
#define WIREBEGIN 11
#define WIREEND 12
#define WIRECLOCK 13
#define WIREWRITE 14
#define WIREREAD 15
#define SPIBEGIN 16
#define SPISETTINGS 17
#define SPITRANSFER 18
#define SPIEND 19
Functions
struct registers pinMode (uint8_t argc, uint8_t *argv)
Change the settings of the Arduino I/O pins.
struct registers digitalWrite (uint8_t argc, uint8_t *argv)
Write a digital (HIGH/LOW) value to the Arduino I/O pins.
struct registers digitalRead (uint8_t argc, uint8_t *argv)
Read a digital value (HIGH/LOW) from the Arduino I/O pins.
struct registers analogWrite (uint8_t argc, uint8_t *argv)
Write an analog value (0-255) to the Arduino I/O pins.
struct registers analogRead (uint8_t argc, uint8_t *argv)
Read an analog value (0-1023) from the Arduino I/O pins.
struct registers servoAttach (uint8_t argc, uint8_t *argv)
Attach a connected servo to a control interface.
struct registers servoDetach (uint8_t argc, uint8_t *argv)
Detach a servo from the the control interface.
struct registers servoWrite (uint8_t argc, uint8_t *argv)
Write a value to the connected servo.
struct registers servoRead (uint8_t argc, uint8_t *argv)
Read a value from the connected servo.
struct registers wireBegin (uint8_t argc, uint8_t *argv)
Begin an I2C connection between the Arduino and a peripheral.
struct registers wireEnd (uint8_t argc, uint8_t *argv)
End an I2C connection between the Arduino and a peripheral.
struct registers wireSetClock (uint8_t argc, uint8_t *argv)
Change the clock speed settings of the I2C connection.
struct registers wireWrite (uint8_t argc, uint8_t *argv)
Write data to the connected I2C peripheral.
struct registers wireRead (uint8_t argc, uint8_t *argv)
Read data from the connected I2C peripheral.
struct registers spiBegin (uint8_t argc, uint8_t *argv)
Begin a SPI connection between the Arduino and a peripheral.
struct registers spiSettings (uint8_t argc, uint8_t *argv)
Change the settings of the SPI connection.
struct registers spiTransferBuf (uint8_t argc, uint8_t *argv)
Exchange data over the SPI connection (Read + Write)
struct registers spiEnd (uint8_t argc, uint8_t *argv)
End a SPI connection between the Arduino and a peripheral.
Detailed Description
Header file for 'Functions.cpp'.
Author
Sam Hutcherson, Chase Wallendorff, Iris Astrid
Date
2023-04-06
Definition in file Functions.h.
Class Documentation
registers
struct registers
A data structure to describe function arguments and return values.
Parameters
count The number of arguments contained within the array 'value'.
value A pointer to an array of bytes (8-bit integral types) that contains the values of the arguments or return values for a command.
Definition at line 53 of file Functions.h.
Class Members
uint8_t count
The number of arguments contained within the array 'value'.
uint8_t * value
A pointer to an array of bytes (8-bit integral types) that contains the values of the arguments or return values for a command.
spi_settings
struct spi_settings
A data structure to describe a SPI connection's configuration settings. Essentially the same as Arduino's 'SPIsettings' object.
Parameters
speed The baud rate/clock speed of the connection.
order The order of bits sent over the wire
mode The clock polarity and phase
Definition at line 68 of file Functions.h.
Class Members
uint8_t mode
The clock polarity and phase.
bool order
The order of bits sent over the wire.
uint32_t speed
The baud rate/clock speed of the connection.
Macro Definition Documentation
ANALOGREAD
#define ANALOGREAD 6
Definition at line 32 of file Functions.h.
ANALOGREFERENCE
#define ANALOGREFERENCE 4
Definition at line 30 of file Functions.h.
ANALOGWRITE
#define ANALOGWRITE 5
Definition at line 31 of file Functions.h.
DIGITALREAD
#define DIGITALREAD 3
Definition at line 29 of file Functions.h.
DIGITALWRITE
#define DIGITALWRITE 2
Definition at line 28 of file Functions.h.
IDLE
#define IDLE 0
Definition at line 26 of file Functions.h.
makeDWord
#define makeDWord (i0, i1, i2, i3) ((uint32_t) (i0 << 24 | i1 << 16 | i2 << 8 | i3))
Combine four 8-bit integral types into one 32-bit integral type, or in simpler terms, reassemble a uint32_t from four uint8_t's.
Definition at line 22 of file Functions.h.
PINMODE
#define PINMODE 1
Definition at line 27 of file Functions.h.
SERVOATTACH
#define SERVOATTACH 7
Definition at line 33 of file Functions.h.
SERVODETACH
#define SERVODETACH 8
Definition at line 34 of file Functions.h.
SERVOREAD
#define SERVOREAD 10
Definition at line 36 of file Functions.h.
SERVOWRITE
#define SERVOWRITE 9
Definition at line 35 of file Functions.h.
SPIBEGIN
#define SPIBEGIN 16
Definition at line 42 of file Functions.h.
SPIEND
#define SPIEND 19
Definition at line 45 of file Functions.h.
SPISETTINGS
#define SPISETTINGS 17
Definition at line 43 of file Functions.h.
SPITRANSFER
#define SPITRANSFER 18
Definition at line 44 of file Functions.h.
WIREBEGIN
#define WIREBEGIN 11
Definition at line 37 of file Functions.h.
WIRECLOCK
#define WIRECLOCK 13
Definition at line 39 of file Functions.h.
WIREEND
#define WIREEND 12
Definition at line 38 of file Functions.h.
WIREREAD
#define WIREREAD 15
Definition at line 41 of file Functions.h.
WIREWRITE
#define WIREWRITE 14
Definition at line 40 of file Functions.h.
Function Documentation
analogRead()
struct registers analogRead (uint8_t argc, uint8_t * argv)
Read an analog value (0-1023) from the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
struct containing the value of pin (10-bit unsigned int contained within a uint16_t)
Definition at line 97 of file Functions.cpp.
References analogRead(), registers::count, registers::value, and VOID_STRUCT.
Referenced by analogRead().
analogWrite()
struct registers analogWrite (uint8_t argc, uint8_t * argv)
Write an analog value (0-255) to the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (3)
argv The arguments to use within the function (pin #, 16-bit value split into 2 8-bit values)
Returns
void (empty struct)
Definition at line 82 of file Functions.cpp.
References analogWrite(), and VOID_STRUCT.
Referenced by analogWrite().
digitalRead()
struct registers digitalRead (uint8_t argc, uint8_t * argv)
Read a digital value (HIGH/LOW) from the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
struct containing the value of pin (1 uint8_t)
Definition at line 62 of file Functions.cpp.
References registers::count, digitalRead(), registers::value, and VOID_STRUCT.
Referenced by digitalRead().
digitalWrite()
struct registers digitalWrite (uint8_t argc, uint8_t * argv)
Write a digital (HIGH/LOW) value to the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, value)
Returns
void (empty struct)
Definition at line 47 of file Functions.cpp.
References digitalWrite(), and VOID_STRUCT.
Referenced by digitalWrite(), and spiTransferBuf().
pinMode()
struct registers pinMode (uint8_t argc, uint8_t * argv)
Change the settings of the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, mode)
Returns
void (empty struct)
Definition at line 32 of file Functions.cpp.
References pinMode(), and VOID_STRUCT.
Referenced by pinMode().
servoAttach()
struct registers servoAttach (uint8_t argc, uint8_t * argv)
Attach a connected servo to a control interface.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
struct containing the ServoIndex (uint8_t), I have no idea what it actually means though (undocumented on Arduino???)
Definition at line 118 of file Functions.cpp.
References registers::count, servo_count, servos, registers::value, and VOID_STRUCT.
servoDetach()
struct registers servoDetach (uint8_t argc, uint8_t * argv)
Detach a servo from the the control interface.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
struct containing the boolean value of the operation's success (uint8_t)
Definition at line 141 of file Functions.cpp.
References registers::count, servos, registers::value, and VOID_STRUCT.
servoRead()
struct registers servoRead (uint8_t argc, uint8_t * argv)
Read a value from the connected servo.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
struct containing the last value written to the servo (uint8_t)
Definition at line 188 of file Functions.cpp.
References registers::count, servos, registers::value, and VOID_STRUCT.
servoWrite()
struct registers servoWrite (uint8_t argc, uint8_t * argv)
Write a value to the connected servo.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, value)
Returns
struct containing the boolean value of the operation's success (uint8_t)
Definition at line 164 of file Functions.cpp.
References registers::count, servos, registers::value, and VOID_STRUCT.
spiBegin()
struct registers spiBegin (uint8_t argc, uint8_t * argv)
Begin a SPI connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 307 of file Functions.cpp.
References spi_settings::mode, spi_settings::order, settings, spi_settings::speed, and VOID_STRUCT.
spiEnd()
struct registers spiEnd (uint8_t argc, uint8_t * argv)
End a SPI connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array (0)
argv The arguments to use within the function (None)
Returns
void (empty struct)
Definition at line 375 of file Functions.cpp.
References VOID_STRUCT.
spiSettings()
struct registers spiSettings (uint8_t argc, uint8_t * argv)
Change the settings of the SPI connection.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 325 of file Functions.cpp.
References makeDWord, spi_settings::mode, spi_settings::order, settings, spi_settings::speed, and VOID_STRUCT.
spiTransferBuf()
struct registers spiTransferBuf (uint8_t argc, uint8_t * argv)
Exchange data over the SPI connection (Read + Write)
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
struct containing the response to the command written (argc - 1 * uint8_t)
Definition at line 343 of file Functions.cpp.
References registers::count, digitalWrite(), spi_settings::mode, spi_settings::order, settings, spi_settings::speed, registers::value, and VOID_STRUCT.
wireBegin()
struct registers wireBegin (uint8_t argc, uint8_t * argv)
Begin an I2C connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 209 of file Functions.cpp.
References VOID_STRUCT.
wireEnd()
struct registers wireEnd (uint8_t argc, uint8_t * argv)
End an I2C connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 221 of file Functions.cpp.
References VOID_STRUCT.
wireRead()
struct registers wireRead (uint8_t argc, uint8_t * argv)
Read data from the connected I2C peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
struct containing the bytes read (num_bytes * uint8_t)
Definition at line 274 of file Functions.cpp.
References registers::count, registers::value, and VOID_STRUCT.
wireSetClock()
struct registers wireSetClock (uint8_t argc, uint8_t * argv)
Change the clock speed settings of the I2C connection.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 233 of file Functions.cpp.
References makeDWord, and VOID_STRUCT.
wireWrite()
struct registers wireWrite (uint8_t argc, uint8_t * argv)
Write data to the connected I2C peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
void (empty struct)
Definition at line 250 of file Functions.cpp.
References VOID_STRUCT.