Modmata: arduino_function_refs Namespace Reference
arduino_function_refs Namespace Reference
Prefix Arduino Library functions so as to specify exactly which function is being called in the namespace, as if the Modmata definition being in a seperate namespace wasn't enough already... *eyerolls*...
Variables
void(&) apinMode (uint8_t, uint8_t) = pinMode
void(&) adigitalWrite (uint8_t, uint8_t) = digitalWrite
int(&) adigitalRead (uint8_t) = digitalRead
void(&) aanalogWrite (uint8_t, int) = analogWrite
int(&) aanalogRead (uint8_t) = analogRead
Detailed Description
Prefix Arduino Library functions so as to specify exactly which function is being called in the namespace, as if the Modmata definition being in a seperate namespace wasn't enough already... *eyerolls*...
Variable Documentation
aanalogRead
int(&) arduino_function_refs::aanalogRead(uint8_t) (uint8_t) = analogRead
Arduino's 'analogRead()'
Definition at line 48 of file Functions.cpp.
Referenced by functions::analogRead().
aanalogWrite
void(&) arduino_function_refs::aanalogWrite(uint8_t, int) (uint8_t , int) = analogWrite
Arduino's 'analogWrite()'
Definition at line 45 of file Functions.cpp.
Referenced by functions::analogWrite().
adigitalRead
int(&) arduino_function_refs::adigitalRead(uint8_t) (uint8_t) = digitalRead
Arduino's 'digitalRead()'
Definition at line 42 of file Functions.cpp.
Referenced by functions::digitalRead().
adigitalWrite
void(&) arduino_function_refs::adigitalWrite(uint8_t, uint8_t) (uint8_t , uint8_t) = digitalWrite
Arduino's 'digitalWrite()'
Definition at line 39 of file Functions.cpp.
Referenced by functions::digitalWrite(), and functions::spiTransferBuf().
apinMode
void(&) arduino_function_refs::apinMode(uint8_t, uint8_t) (uint8_t , uint8_t) = pinMode
Arduino's 'pinMode()'
Definition at line 36 of file Functions.cpp.
Referenced by functions::pinMode().