Modmata: functions Namespace Reference
functions Namespace Reference
Distinguish Modmata functions from standard Arduino functions with a namespace.
Functions
registers pinMode (uint8_t argc, uint8_t *argv)
Change the settings of the Arduino I/O pins.
registers digitalWrite (uint8_t argc, uint8_t *argv)
Write a digital (HIGH/LOW) value to the Arduino I/O pins.
registers digitalRead (uint8_t argc, uint8_t *argv)
Read a digital value (HIGH/LOW) from the Arduino I/O pins.
registers analogWrite (uint8_t argc, uint8_t *argv)
Write an analog value (0-255) to the Arduino I/O pins.
registers analogRead (uint8_t argc, uint8_t *argv)
Read an analog value (0-255) from the Arduino I/O pins.
registers servoAttach (uint8_t argc, uint8_t *argv)
Attach a connected servo to a control interface.
registers servoDetach (uint8_t argc, uint8_t *argv)
Detach a servo from the the control interface.
registers servoWrite (uint8_t argc, uint8_t *argv)
Write a value to the connected servo.
registers servoRead (uint8_t argc, uint8_t *argv)
Read a value from the connected servo.
registers wireBegin (uint8_t argc, uint8_t *argv)
Begin an I2C connection between the Arduino and a peripheral.
registers wireEnd (uint8_t argc, uint8_t *argv)
End an I2C connection between the Arduino and a peripheral.
registers wireSetClock (uint8_t argc, uint8_t *argv)
Change the clock speed settings of the I2C connection.
registers wireWrite (uint8_t argc, uint8_t *argv)
Write data to the connected I2C peripheral.
registers wireRead (uint8_t argc, uint8_t *argv)
Read data from the connected I2C peripheral.
registers spiBegin (uint8_t argc, uint8_t *argv)
Begin a SPI connection between the Arduino and a peripheral.
registers spiSettings (uint8_t argc, uint8_t *argv)
Change the settings of the SPI connection.
registers spiTransferBuf (uint8_t argc, uint8_t *argv)
Exchange data over the SPI connection (Read + Write)
registers spiEnd (uint8_t argc, uint8_t *argv)
End a SPI connection between the Arduino and a peripheral.
Detailed Description
Distinguish Modmata functions from standard Arduino functions with a namespace.
Function Documentation
analogRead()
registers functions::analogRead (uint8_t argc, uint8_t * argv)
Read an analog value (0-255) from the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
result: a 'registers' struct holding the return values of the called function (16-bit pin value split into 2 8-bit values)
Definition at line 138 of file Functions.cpp.
References arduino_function_refs::aanalogRead, registers::count, and registers::value.
Referenced by modmata::ModmataClass::begin().
analogWrite()
registers functions::analogWrite (uint8_t argc, uint8_t * argv)
Write an analog value (0-255) to the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (3)
argv The arguments to use within the function (pin #, 16-bit value split into 2 8-bit values)
Returns
result: a 'registers' struct holding the return values of the called function (empty, in this case)
Definition at line 120 of file Functions.cpp.
References arduino_function_refs::aanalogWrite, and registers::count.
Referenced by modmata::ModmataClass::begin().
digitalRead()
registers functions::digitalRead (uint8_t argc, uint8_t * argv)
Read a digital value (HIGH/LOW) from the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
result: a 'registers' struct holding the return values of the called function (value of pin)
Definition at line 96 of file Functions.cpp.
References arduino_function_refs::adigitalRead, registers::count, and registers::value.
Referenced by modmata::ModmataClass::begin().
digitalWrite()
registers functions::digitalWrite (uint8_t argc, uint8_t * argv)
Write a digital (HIGH/LOW) value to the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, value)
Returns
result: a 'registers' struct holding the return values of the called function (empty, in this case)
Definition at line 78 of file Functions.cpp.
References arduino_function_refs::adigitalWrite, and registers::count.
Referenced by modmata::ModmataClass::begin().
pinMode()
registers functions::pinMode (uint8_t argc, uint8_t * argv)
Change the settings of the Arduino I/O pins.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, mode)
Returns
result: a 'registers' struct holding the return values of the called function (empty, in this case)
Definition at line 60 of file Functions.cpp.
References arduino_function_refs::apinMode, and registers::count.
Referenced by modmata::ModmataClass::begin().
servoAttach()
registers functions::servoAttach (uint8_t argc, uint8_t * argv)
Attach a connected servo to a control interface.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 163 of file Functions.cpp.
References registers::count, servo_count, servos, and registers::value.
Referenced by modmata::ModmataClass::begin().
servoDetach()
registers functions::servoDetach (uint8_t argc, uint8_t * argv)
Detach a servo from the the control interface.
Parameters
argc The number of arguments contained within the 'argv' array (1)
argv The arguments to use within the function (pin #)
Returns
result: a 'registers' struct holding the return values of the called function (1 on success)
Definition at line 191 of file Functions.cpp.
References registers::count, servos, and registers::value.
Referenced by modmata::ModmataClass::begin().
servoRead()
registers functions::servoRead (uint8_t argc, uint8_t * argv)
Read a value from the connected servo.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 250 of file Functions.cpp.
References registers::count, servos, and registers::value.
Referenced by modmata::ModmataClass::begin().
servoWrite()
registers functions::servoWrite (uint8_t argc, uint8_t * argv)
Write a value to the connected servo.
Parameters
argc The number of arguments contained within the 'argv' array (2)
argv The arguments to use within the function (pin #, value)
Returns
result: a 'registers' struct holding the return values of the called function (1 on success)
Definition at line 220 of file Functions.cpp.
References registers::count, servos, and registers::value.
Referenced by modmata::ModmataClass::begin().
spiBegin()
registers functions::spiBegin (uint8_t argc, uint8_t * argv)
Begin a SPI connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 392 of file Functions.cpp.
References registers::count, spi_settings::mode, spi_settings::order, settings, and spi_settings::speed.
Referenced by modmata::ModmataClass::begin().
spiEnd()
registers functions::spiEnd (uint8_t argc, uint8_t * argv)
End a SPI connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array (0)
argv The arguments to use within the function (None)
Returns
result: a 'registers' struct holding the return values of the called function (empty, in this case)
Definition at line 471 of file Functions.cpp.
References registers::count.
Referenced by modmata::ModmataClass::begin().
spiSettings()
registers functions::spiSettings (uint8_t argc, uint8_t * argv)
Change the settings of the SPI connection.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 414 of file Functions.cpp.
References registers::count, spi_settings::mode, spi_settings::order, settings, and spi_settings::speed.
Referenced by modmata::ModmataClass::begin().
spiTransferBuf()
registers functions::spiTransferBuf (uint8_t argc, uint8_t * argv)
Exchange data over the SPI connection (Read + Write)
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 435 of file Functions.cpp.
References arduino_function_refs::adigitalWrite, registers::count, spi_settings::mode, spi_settings::order, settings, spi_settings::speed, and registers::value.
Referenced by modmata::ModmataClass::begin().
wireBegin()
registers functions::wireBegin (uint8_t argc, uint8_t * argv)
Begin an I2C connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 278 of file Functions.cpp.
References registers::count.
Referenced by modmata::ModmataClass::begin().
wireEnd()
registers functions::wireEnd (uint8_t argc, uint8_t * argv)
End an I2C connection between the Arduino and a peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 293 of file Functions.cpp.
References registers::count.
Referenced by modmata::ModmataClass::begin().
wireRead()
registers functions::wireRead (uint8_t argc, uint8_t * argv)
Read data from the connected I2C peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 353 of file Functions.cpp.
References registers::count, and registers::value.
Referenced by modmata::ModmataClass::begin().
wireSetClock()
registers functions::wireSetClock (uint8_t argc, uint8_t * argv)
Change the clock speed settings of the I2C connection.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 308 of file Functions.cpp.
References registers::count.
Referenced by modmata::ModmataClass::begin().
wireWrite()
registers functions::wireWrite (uint8_t argc, uint8_t * argv)
Write data to the connected I2C peripheral.
Parameters
argc The number of arguments contained within the 'argv' array
argv The arguments to use within the function
Returns
result: a 'registers' struct holding the return values of the called function
Definition at line 326 of file Functions.cpp.
References registers::count.
Referenced by modmata::ModmataClass::begin().